import { PROJECTS } from '../constants';
export default function Projects() {
  return <section id="projects" className="section wrap"><div className="section-top"><div><p className="eyebrow">02 / SELECTED WORK</p><h2>From idea to working product.</h2></div><a className="text-link" href="https://github.com/raselislam29" target="_blank" rel="noreferrer">More on GitHub ↗</a></div>
    <div className="project-grid">{PROJECTS.filter(p => p.kind === 'product').map((project, index) => <article className={`project-card project-${project.id}`} key={project.id}>
      <div className="project-art" aria-hidden="true">
        {index === 0 ? <div className="openmd-art"><div className="mock-top"><b>open<span>md</span></b><span>Care, connected.</span></div><div className="mock-body"><div className="mock-sidebar"><i /><i /><i /><i /></div><div className="mock-content"><span>WORKSPACE OVERVIEW</span><strong>A clearer view of care.</strong><div className="mock-tiles"><div>Practices<span>One workspace</span></div><div>Providers<span>Connected teams</span></div></div><div className="mock-row"><i /> Scheduling <span>→</span></div><div className="mock-row"><i /> Team & access <span>→</span></div></div></div></div> : index === 1 ? <div className="flat-art"><span className="mono">FINDMYFLAT</span><strong>Find a place.<br />Make it yours.</strong><div className="house-scene"><div className="building building-a" /><div className="building building-b" /><div className="building building-c" /><span className="map-pin">⌂</span></div><span className="mock-search">⌕ &nbsp; Your next neighborhood <b>↗</b></span></div> : <div className="water-art"><span className="mono">LITTLE REMINDERS. BETTER DAYS.</span><div className="water-drop" /><strong>A moment to recharge.</strong><span className="reminder-pill">Time for a water break <span>↗</span></span></div>}
        <span className="preview-label">UI CONCEPT</span>
      </div>
      <div className="project-body"><div className="project-kicker">{index === 0 ? 'HEALTHCARE PLATFORM · SENIOR CAPSTONE' : index === 1 ? 'WEB APPLICATION' : 'DESKTOP APPLICATION'}</div><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-links"><a href={project.githubUrl} target="_blank" rel="noreferrer">View code <span aria-hidden="true">↗</span></a>{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noreferrer">Live site ↗</a>}</div></div>
    </article>)}</div>
    <details className="supporting-work"><summary>Also explored <span>Security & risk assessment</span><span aria-hidden="true">+</span></summary><div className="supporting-grid">{PROJECTS.filter(p => p.kind === 'security').map(p => <article key={p.id}><h3>{p.title}</h3><p>{p.description}</p>{p.githubUrl && <a className="text-link" href={p.githubUrl} target="_blank" rel="noreferrer">View code ↗</a>}</article>)}</div></details>
  </section>;
}
